Solkraft/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from shop import views

# These are the root url patterns

urlpatterns = [
    # The admin panel is included
    path('admin/', admin.site.urls),
    # As well as all the urls from the different applications that we've created
    path('questions/', include('questions.urls')),
    path('plate/', include('django_spaghetti.urls')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls')),
    path('profile/', include('customer.urls', namespace='profile')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('parameter-autocomplete/', views.ParameterAutocomplete,
         name='parameter-autocomplete'),
    # and social-auth from Django social auth to add registration and login via social media
    # The login with Facebook and Google worked fine, but solely with an older version of django-social-auth which sometimes led to installation problems and thus we removed it from our website
    # path('social-auth/', include('social_django.urls', namespace='social')),
    # and two more paths from our side
    path('newsletter/', include('newsletter.urls')),
    path("password_reset", views.password_reset_request, name="password_reset"),
]

# Setting the media folder
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

# The name is used to identify the app
# If one wants to use any function, e.g. allblogs, one needs to write blog:allblogs, instead of simply allblogs
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'blog'

urlpatterns = [
    path('', views.allblogs, name='allblogs'),
    path('games.html', views.games, name='games'),
    # The blog post is identified by it's id, which is an intger
    path('<int:post_id>', views.blog_post, name='blog_post')
]

contact/urls.py
from django.contrib import admin
from django.urls import path
from contact import views as contact_views

# The name is used to identify the app
# If one wants to use any function, in this case contact, one needs to write contact:contact, instead of simply contact
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
# Another benefit is that contact can be used as a name for another path in another application
app_name = 'contact'

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('contact/', contact_views.contact_view, name='contact'),
]

newsletter/urls.py
from . import views
from django.urls import path

# The name is used to identify the app
# If one wants to use any function, e.g. new, one needs to write newsletter:new, instead of simply new
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'newsletter'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('new//confirm/', views.confirm, name='confirm'),
    path('delete/', views.delete, name='delete'),
    path('newsletter_registration/', views.newsletter_registration,
         name="newsletter_registration"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

# The name is used to identify the application
# If one wants to use any function, e.g. add_to_wishlist, one needs to write shop:add_to_wishlist, instead of simply add_to_wishlist
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
# Another benefit is that the same name can be given to another path in a different application
app_name = 'shop'

urlpatterns = [
    # Our staff works with the admin panel for the most part, though they also have their dedicated app with templates/function specifically defined to make their work easier for them
    path('admin/', admin.site.urls),
    #     In the home page 4 random products are displayed (they are different every time you'll load the page)
    path('', views.random_products, name='random_products'),
    #     We added some static pages for information, e.g. this about us and the below terms of service page
    path('about_us.html', views.about_view, name='about_us'),
    path('terms_of_service.html', views.terms_view, name='terms_of_service'),
    #     A wishlist with all needed functions was created as well
    path('wishlist/', views.WishListView.as_view(), name='wishlist'),
    #     The product can be added from the product page and the product cards in the product_list, random_products and search
    path('add_to_wishlist/<slug:product_slug>',
         views.add_to_wishlist, name="add_to_wishlist"),
    #     And the wishlist can be deleted in the product page and inside the wishlist
    #     If a user tries to delete an item from the list, which isn't in his/her wishlist, the user is redirected to the wishlist without any changes
    path('delete_from_wishlist/<slug:product_slug>', views.delete_from_wishlist,
         name='delete_from_wishlist'),
    #     More static sites
    path('privacy_policy.html', views.privacy_view, name='privacy_policy'),
    path('shipping_policy.html', views.policy_view, name='shipping_policy'),
    #     The summary contains information about the offered services and allows the user to register for the plant workshops
    path('summary.html', views.summary_view, name='summary'),
    #     The products are displayed in a list and pagination exists which ensures that our website doesn't take too long to load
    path('products/', views.product_list, name='product_list'),
    path('<int:page>/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    #     The category slug is needed to ensure that only the products of a specific category are shown, if a category is selected by the user
    path('<slug:category_slug>/<int:page>/',
         views.product_list, name='product_list_by_category'),
    #     Of course every item has its dedicated page with further information about it
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    #     Our user can add reviews, but they can also delete their own reviews
    path('delete_review/<int:id>', views.delete_review,
         name='delete_review'),
    #     A search was implemented as well. It isn't too smart, but therefore it wasn't simply taken from an existing source but created by ourselves
    #     We had to use re_path, since we had to add the dollar sign at the end to ensure that the search works well for every type of user input
    re_path(r'^searching/<str:phrase>/$',
            views.searching, name='searching'),
    #   Pagination shouldn't be needed for the search as of now, but potentially the webshop will add more products later on and someday it might very well be needed
    path('searching/<int:page>/<str:phrase>',
         views.searching, name='searching'),
]

blog/models.py
from django.db import models
from django.utils import timezone


class BlogEntry(models.Model):
    title = models.CharField(max_length=100)
    pub_date = models.DateTimeField(verbose_name='Publication Date')
    # The image is uploaded to the media folder and there it is saved inside the images folder
    image = models.ImageField(upload_to='images/')
    body = models.TextField()

    class Meta:
        # We order the blog entries by the publication date. The - is needed to have the latest blog entry first
        ordering = ['-pub_date', ]
        # We've added a verbose name to display it more nicely in the admin panel
        verbose_name = 'blog entry'
        # and BlogEntrys would be rather bad English anyways and we wouldn't want that
        verbose_name_plural = 'blog entries'

    def __str__(self):
        return self.title

    def pub_date_pretty(self):
        # We improve the look of the publication date, before returning it
        self.pub_date = self.pub_date.strftime("%d %b %Y")
        return self.pub_date

    def summary(self):
        # If the text of the blog entry is smaller or equal to 100 words, we can display it entirely
        if len(self.body.split()) <= 100:
            return self.body
        else:
            # Otherwise, we can only show the first 100 words
            words = self.body.split()
            word_list = []
            i = 0
            while i < 100:
                word_list += words[i]+" "
                i += 1
                # and add three dots to indicate that this isn't the entire text of the post.
            words = "".join(word_list)+" ..."
            return words

blog/views.py
from django.shortcuts import render, get_object_or_404
from . import models


def allblogs(request):
    blogentries = models.BlogEntry.objects
    # As context, we return all the objects within BlogEntry, as we want to display every blog entry.
    return render(request, 'allblogs.html', {"blogs": blogentries})


def blog_post(request, post_id):
    # To display a blog post, we have to retrive it and if we cannot find it, we have to return a 404 message
    single_post = get_object_or_404(models.BlogEntry, pk=post_id)
    # Of course, the single post is the context in this case
    return render(request, 'blogpost.html', {'single_blog': single_post})


def games(request):
    # The games site is a static page
    return render(request, 'games.html')

blog/templates/allblogs.html
<!DOCTYPE html>
<html lang="de">
{% load static%}


{% block favicon %}
<link rel="shortcut icon" href="{% static 'images/GreenOasis0.png' %}" />
{% endblock %}

<!-- Since the blog somewhat differs from the rest of the application, as it can also be used without the shop, we have to define somethings here, as we do not extends the base.html -->

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>GreenOasis Pflanzen Blog</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>
  <!-- Simple navbar -->
  <div class="bg">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'shop:summary' %}"><img src="{% static 'images/GreenOasis_Logo.png' %}"
          height=40 />
        Welcome!</a>
      <!-- We decided not to add more information/links to the navbar, but one could do so responsively with this section -->
      <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button> -->
    </nav>
    <!-- Show picutre and header -->
    <main role="main">
      <div align="center">
        <img src="{% static 'images/Plants.jpg' %}" style="width: 100%;" />
        <h1 class="elegant">Solkraft's Blog about green enery solutions</h1>
      </div>
      <br />

      <!-- CSS used for the games button -->
      <style>
        .hidden {
          display: none;
        }

        .unhidden {
          display: block;
        }
      </style>
      <!-- JavaScript to hide or unhide the community chess game with a simple button click -->
      <script type="text/javascript">
        function unhide(clickedButton, divID) {
          var item = document.getElementById(divID);
          if (item) {
            if (item.className == 'hidden') {
              item.className = 'unhidden';
              clickedButton.value = 'zuklappen'
            } else {
              item.className = 'hidden';
              clickedButton.value = 'Schach'
            }
          }
        }

      </script>

      <!-- Of course, one wants to see the newest blog entries first and potentially one wants to go to the webshop as well -->
      <br />
      <h2 align=center>Recent posts</h2>
      <a href="{% url 'shop:random_products' %}" style="color:goldenrod">
        <h3 align=center>Zum Webshop</h3>
      </a>
      <hr>
    </main>

    <div class="container">
      <!-- We iterate through every blog post -->
      {% for post in blogs.all %}
      <span class='underline'>
        <!-- Show the title of the post -->
        <a href="{{post.id}}" style="color:green">
          <h3 class="elegant">{{post.title}}</h3>
        </a>
      </span><br />
      <!-- and the nicely formatted date -->
      {{post.pub_date_pretty}}
      <!-- As well as the first 100 words of the blog post, to give people an idea on what they are about to read, if they decide to click on the post -->
      <p>{{post.body | linebreaks | truncatewords:100}} </p>
      <!-- Once could also add a summary, but the first 100 words are already telling everything which needs to be told -->
      <!-- 
    <p>{{post.summary}} </p> 
    -->
      <!-- A small image is displayed for every blog post -->
      <div style="text-align: center;"><img class="img-fluid" src="/media/{{post.image}}" width="300" height="200">
      </div><br />
      {% endfor %}
      <br />
      <!-- A small area with community games is also provided for our customers -->
      <h3>Compete against the community and prove yourself in selected games!</h3>
      <!-- The chess games is hidden below a button and one can play against a real human -->
      <div id="about" class="hidden" align="center">
        <div class="content3">
          <h5>Schach spielen</h5>
          <script src="http://www.startspiele.de/einbinden/schach.jhtm"></script>
        </div>
        <br /><br />
      </div>
      <input type="button" class="btn btn-outline-dark" onclick="unhide(this, 'about') " value="Schach spielen">
      <br />
      <!-- A small gaming site with more games is provided via this link -->
      Would you like to play more games? Then visit our <a href='{% url "blog:games"%}' style="color:goldenrod">game
        page</a>
    </div> <br />
    <br /><br />
    <!-- Newsletter -->
    <center>
      <!-- One can register for our newsletter by clicking on the self-designed image -->
      <a href="{% url 'newsletter:newsletter_registration' %}"><img src="{% static 'images/Newsletter.jpg' %}"
          width='60%' /></a>
    </center><br />
    <!-- The footer from the footer.html is included into this template -->
    {% include 'footer.html' %}
</body>

</html>

blog/templates/blogpost.html
<!DOCTYPE html>
<html lang="de">
{% load static%}

<!-- The favicon and further information needs to be defined, as this template doesn't extend any html -->
{% block favicon %}
<link rel="shortcut icon" href="{% static 'images/GreenOasis0.png' %}" />
{% endblock %}


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{single_blog.title}}</title>
  <!-- The only ressource which isn't directly from GreenOasis is Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}" />

</head>

<body>
  <!-- Simple navbar -->
  <div class="bg">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'shop:summary' %}"><img src="{% static 'images/GreenOasis_Logo.png' %}"
          height=40 />
        Welcome!</a>
      <!-- We decided not to add more information/links to the navbar, but one could do so responsively with this section -->
      <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button> -->
    </nav>
    <img src="{% static 'images/Plants.jpg' %}" style="width: 100%;" />
    <div style="text-align: center;">
      <main role="main">
        <br /><br />
        <!-- The title of the blog is shown in an elegant manner -->
        <h1 class="elegant">{{single_blog.title}}</h1>
        <br /><br />
      </main>
    </div>
    <div class="container">
      <!-- The linebreaks command replaces single newline characters with <br> tags and wraps lines of text separated by two newline characters in <p> tags. -->
      <p>{{single_blog.body|linebreaks}} </p>
      <!-- The blog post image is also shown in the blogpost itself -->
      <img class="img-fluid" src="/media/{{single_blog.image}}" height="200" width="200" /><br />
      <br />
      <!-- One can get back to all the blog posts with the help of a button or the return button from the browser one uses -->
      <a href="{% url 'blog:allblogs' %}" class="btn btn-success" role="button">Blogauswahl</a>
    </div>
  </div>
  <br /> <br />
  <!-- Newsletter registration is possible via a click on the self-designed image -->
  <center>
    <a href="{% url 'newsletter:newsletter_registration' %}"><img src="{% static 'images/Newsletter.jpg' %}"
        width='60%' /></a>
  </center><br />
  <!-- The footer is included, as it is the case in allblogs.html -->
  {% include 'footer.html' %}
</body>

</html>

blog/templates/footer.html
{% load static %}
<!-- Bootstrap CSS -->
<!-- Bootstrap is the only source which is not directly from GreenOasis -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- Bootstrap core CSS -->
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800,300" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/base.css' %}">

<script src="https://kit.fontawesome.com/7ddcda0d1c.js" crossorigin="anonymous"></script>
<!-- Ensure optimal rendering on mobile devices. -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Ensure optimal Internet Explorer compatibility -->
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<!-- The footer -->
<footer class="py-5 bg-success">
    <div class="container">
        <div class="row">
            <!-- Static files which inform users about important legal aspects, as well as information about GreenOasis and its services -->
            <div class="col-md-4">
                <h5 class="mb-4 text-white"><u><strong>About us</strong></u></h5>
                <a class="text-white text-decoration-none" href="{% url 'shop:about_us' %}">
                    <p class="text-white"><i class="fab fa-pagelines" style="font-size: 30px"></i>
                        About us
                </a></p>

                <a class="text-white text-decoration-none" href="{% url 'shop:terms_of_service' %}">
                    <p class="text-white"><i class="fas fa-file-signature" style="font-size: 20px;"></i>
                        Terms of use
                </a></p>

                <a class="text-white text-decoration-none" href="{% url 'shop:shipping_policy' %}">
                    <p class="text-white"><i class="fas fa-truck" style="font-size: 18px;"></i>
                        Shipping policy
                </a></p>

                <a class="text-white text-decoration-none" href="{% url 'shop:privacy_policy' %}">
                    <p class="text-white"><i class="fas fa-lock h5"></i>&nbsp; Privacy Policy
                </a></p>

            </div>
            <!-- Of course different contact options are also provided -->
            <div class="col-md-4">
                <h5 class="mb-4 text-white"><u><strong>Contact us</strong></u></h5>
                <a class="text-white text-decoration-none" href="{% url 'contact:contact' %}">
                    <i class="fas fa-comments h4 pb-3"></i> Contact form</a>
                <p class="text-white"><i class="fas fa-map-marker-alt h4"></i> Wan Chai, 105 Kennedy Road</p>
                <p class="text-white"><i class="fas fa-phone-alt h4"></i>
                    <a href="tel:+852747744474" style="color:whitesmoke">+852 747744474</a>
                </p>
                <p class="text-white"><i class="fas fa-envelope h4"></i>
                    <a href="mailto:Solkraft.GreenEnergySolutions@gmail.com"
                        style="color: whitesmoke">Solkraft.GreenEnergySolutions@gmail.com</a>
                </p>

            </div>
            <!-- Further services are also provided below, which of course includes our shop -->
            <div class="col-md-4">
                <h5 class="mb-4 text-white"><u><strong>Further offers</strong></u></h5>
                <a class="text-light text-decoration-none" href="{% url 'shop:product_list' %}">
                    <p class="text-white"><i class="fas fa-shopping-bag h4"></i>
                        Shop
                    </p>
                </a>
                <a class="text-white text-decoration-none" href="{% url 'questions' %}">
                    <p class="text-white"></p><i class="fas fa-question-circle h4"></i> Q&A
                </a>
                <a class="text-white text-decoration-none" href="{% url 'profile:contact' %}">
                    <p class="text-white"></p><i class="fas fa-paper-plane h4"></i> Refunds
                </a>
                </a></p>
            </div>
        </div>
    </div>
</footer>
<!-- Copyright -->
<div class="text-center p-3" style="background-color:dimgray">
    <!-- The actual copyright section -->
    <span style="color:white"> © 2021 Copyright:</span>
    <a class="text-white" href='{% url "shop:random_products" %}'>Solkraft</a>
</div>
<!-- Copyright -->

blog/templates/games.html
<!DOCTYPE html>
<html lang="de">
{% load static%}

<head>
    {% block favicon %}
    <link rel="shortcut icon" href="{% static 'images/GreenOasis0.png' %}" />
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title class="elegeant">Game page</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'shop:summary' %}"><img src="{% static 'images/GreenOasis_Logo.png' %}"
                height=40 />
            Welcome!</a>
        <!-- We decided not to add more information/links to the navbar, but one could do so responsively with this section -->
        <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button> -->
    </nav>
    <img src="{% static 'images/Plants.jpg' %}" style="width: 100%;" />
    <br /> <br />

    <h1 class="elegant" style="margin-left:37%">Gaming</h1>
    <br />

    <!-- Table which holds different games which can be played with the plant community -->
    <table width=" 50%" style="margin-left: auto; margin-right: auto">
        <tr>
            <td>
                <script src="http://www.startspiele.de/einbinden/go.jhtm"></script>
            </td>
            <td>
                <script src="http://www.startspiele.de/einbinden/sudoku.jhtm"></script>
            </td>
        </tr>
        <tr>
            <td>
                <script src="http://www.startspiele.de/einbinden/viergewinnt.jhtm"></script>
            </td>
            <td>
                <script src="http://www.startspiele.de/einbinden/memory.jhtm"></script>
            </td>
        </tr>
        <tr>
            <td>
                <script src="http://www.startspiele.de/einbinden/schach.jhtm"></script>
            </td>
            <td>
                <script src="http://www.startspiele.de/einbinden/9ball.jhtm"></script>
            </td>
        </tr>
    </table>
    <br /> <br />

    <h4 class="text-success" style="margin-left:37%">Plants <span style="color:black">vs.</span> <span
            style="color:red">Zombies</span></h4>
    <!-- iframes are a more secure method of embedding content from other sites onto your own page -->
    <!-- As this loads a game, we cannot set the sandbox element, as the game wouldn't work in that case  -->
    <!-- Of course, clickjacking protection was ensured with the help of X-Frame-Options and no sensitive-data is submitted in this case -->
    <!-- It uses HTTPS and thus the data cannot be easily changed by malicious parties -->
    <!-- No connection to retrogames is held when playing the game and a content security policy was set as well -->
    <!-- Moreover, it was ensured that the game only loads after the user clicks on the Play Now button -->
    <iframe class="embed-responsive embed-responsive-16by9"
        src="https://www.retrogames.cc/embed/41654-plants-vs-zombies-usa.html" width="600" height="450" frameborder="no"
        allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" scrolling="no"></iframe>
    <p></p>

    <br /> <br />
    <center>
        <!-- Newsletter registration is possible via a click on the self-designed image -->
        <a href="{% url 'newsletter:newsletter_registration' %}"><img src="{% static 'images/Newsletter.jpg' %}"
                width='60%' /></a>
    </center><br />
    <!-- The footer is included, as it is the case in allblogs.html -->
    {% include 'footer.html' %}
</body>

</html>