Solkraft/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from shop import views

# These are the root url patterns

urlpatterns = [
    # The admin panel is included
    path('admin/', admin.site.urls),
    # As well as all the urls from the different applications that we've created
    path('questions/', include('questions.urls')),
    path('plate/', include('django_spaghetti.urls')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls')),
    path('profile/', include('customer.urls', namespace='profile')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('parameter-autocomplete/', views.ParameterAutocomplete,
         name='parameter-autocomplete'),
    # and social-auth from Django social auth to add registration and login via social media
    # The login with Facebook and Google worked fine, but solely with an older version of django-social-auth which sometimes led to installation problems and thus we removed it from our website
    # path('social-auth/', include('social_django.urls', namespace='social')),
    # and two more paths from our side
    path('newsletter/', include('newsletter.urls')),
    path("password_reset", views.password_reset_request, name="password_reset"),
]

# Setting the media folder
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

# The name is used to identify the app
# If one wants to use any function, e.g. allblogs, one needs to write blog:allblogs, instead of simply allblogs
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'blog'

urlpatterns = [
    path('', views.allblogs, name='allblogs'),
    path('games.html', views.games, name='games'),
    # The blog post is identified by it's id, which is an intger
    path('<int:post_id>', views.blog_post, name='blog_post')
]

cart/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

# The name is used to identify the app
# If one wants to use any function, e.g. cart_add, one needs to write cart:cart_add, instead of simply cart_add
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'cart'

urlpatterns = [
    # The checkout shows the cart details, offers a voucher option, a delivery selection and offers the option to place an order
    path('checkout/', views.cart_detail, name='cart_detail'),
    # Cart add is used to add a selected number of products to the cart
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    # Cart_add_one solely adds the product to the cart once (used outside of the product detail page and for the + button in the cart)
    path('add/<int:product_id>/', views.cart_add_one, name='cart_add_one'),
    # Cart remove deletes the product from the cart
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    # Cart remove one decreases the quantity by one (though it was implemented in a way, which makes it possible to decrease the quantity by a given amount)
    path('remove_one/<int:product_id>/',
         views.cart_remove_one, name='cart_remove_one'),
    #  Of course, checkout is possible
    path('cart_checkout/<int:id>', views.cart_checkout, name='cart_checkout'),
    # The customer needs to choose a shipping address
    path('choose_address/<int:id>', views.choose_address, name='choose_address'),
    # If the order is complete, a template is shown which summarizes the important information
    path('order_complete/', views.order_complete, name='order_complete'),
    path('order_bank_transfer', views.order_bank_transfer,
         name='order_bank_transfer'),
    # If the user pays via bank transfer, another method is needed, as order_complete works with PayPal
    path('cash_on_delivery', views.cash_on_delivery, name='cash_on_delivery'),
    # If the user wants to collect the products from our Solkraft shop, the procedure differs as well
    path('collection', views.collection, name='collection')

]

customer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

# The name is used to identify the app
# If one wants to use any function, e.g. show_profile, one needs to write profile:show_profile, instead of simply show_profile
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'profile'

urlpatterns = [
    path('show/', views.show_profile, name='show_profile'),
    path('contact', views.make_Complaint, name='contact'),
    path('orders/', views.show_orders, name='show_orders'),
    path('update/', views.revise_profile, name='update'),
]

newsletter/urls.py
from . import views
from django.urls import path

# The name is used to identify the app
# If one wants to use any function, e.g. new, one needs to write newsletter:new, instead of simply new
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'newsletter'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('new//confirm/', views.confirm, name='confirm'),
    path('delete/', views.delete, name='delete'),
    path('newsletter_registration/', views.newsletter_registration,
         name="newsletter_registration"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

# The name is used to identify the application
# If one wants to use any function, e.g. add_to_wishlist, one needs to write shop:add_to_wishlist, instead of simply add_to_wishlist
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
# Another benefit is that the same name can be given to another path in a different application
app_name = 'shop'

urlpatterns = [
    # Our staff works with the admin panel for the most part, though they also have their dedicated app with templates/function specifically defined to make their work easier for them
    path('admin/', admin.site.urls),
    #     In the home page 4 random products are displayed (they are different every time you'll load the page)
    path('', views.random_products, name='random_products'),
    #     We added some static pages for information, e.g. this about us and the below terms of service page
    path('about_us.html', views.about_view, name='about_us'),
    path('terms_of_service.html', views.terms_view, name='terms_of_service'),
    #     A wishlist with all needed functions was created as well
    path('wishlist/', views.WishListView.as_view(), name='wishlist'),
    #     The product can be added from the product page and the product cards in the product_list, random_products and search
    path('add_to_wishlist/<slug:product_slug>',
         views.add_to_wishlist, name="add_to_wishlist"),
    #     And the wishlist can be deleted in the product page and inside the wishlist
    #     If a user tries to delete an item from the list, which isn't in his/her wishlist, the user is redirected to the wishlist without any changes
    path('delete_from_wishlist/<slug:product_slug>', views.delete_from_wishlist,
         name='delete_from_wishlist'),
    #     More static sites
    path('privacy_policy.html', views.privacy_view, name='privacy_policy'),
    path('shipping_policy.html', views.policy_view, name='shipping_policy'),
    #     The summary contains information about the offered services and allows the user to register for the plant workshops
    path('summary.html', views.summary_view, name='summary'),
    #     The products are displayed in a list and pagination exists which ensures that our website doesn't take too long to load
    path('products/', views.product_list, name='product_list'),
    path('<int:page>/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    #     The category slug is needed to ensure that only the products of a specific category are shown, if a category is selected by the user
    path('<slug:category_slug>/<int:page>/',
         views.product_list, name='product_list_by_category'),
    #     Of course every item has its dedicated page with further information about it
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    #     Our user can add reviews, but they can also delete their own reviews
    path('delete_review/<int:id>', views.delete_review,
         name='delete_review'),
    #     A search was implemented as well. It isn't too smart, but therefore it wasn't simply taken from an existing source but created by ourselves
    #     We had to use re_path, since we had to add the dollar sign at the end to ensure that the search works well for every type of user input
    re_path(r'^searching/<str:phrase>/$',
            views.searching, name='searching'),
    #   Pagination shouldn't be needed for the search as of now, but potentially the webshop will add more products later on and someday it might very well be needed
    path('searching/<int:page>/<str:phrase>',
         views.searching, name='searching'),
]

cart/models.py
from django.db import models
from coupons.models import Coupon
from shop.models import Product
from django.contrib.auth.models import User
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from .cart import Cart

# The models are saved in the database


class Order(models.Model):
    # Of course the order component needs the order model and the order model needs a customer to link that order to
    # The customer should not be deleted by any means when deleting his/her order
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    # The is confirmed boolean tells us whether the order was paid or not. Initially it is not paid.
    is_confirmed = models.BooleanField(default=False)
    # Created at saves the information on when the order was placed by the customer
    created_at = models.DateTimeField(auto_now_add=True)
    # The delivery type is also important to ensure that our staff sends the product with the right delivery option
    delivery_type = models.CharField(max_length=100)
    # The price of the delivery is needed to get the total price
    delivery_price = models.DecimalField(max_digits=10, decimal_places=2, validators=[
                                         MinValueValidator(Decimal('0.00'))])
    # The price could be used here, but we decided against it, as we could simply define a method to get that information
    # price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    # A payment_id is used which is either generated by PayPal or a random number, if the customer pays with credit card or bank transfer
    payment_id = models.CharField(max_length=1000, null=True)
    # The customer needs to enter his/her first name(s)
    name = models.CharField(max_length=100, default="None")
    # As well has his/her surname
    surname = models.CharField(max_length=100, default="None")
    # The default address is also set to None, as the customer has to fill in that information
    address = models.CharField(max_length=200, default="None")
    city = models.CharField(max_length=100, default="None")
    # The postal code is needed to get the delivery to the correct city/village
    postal_code = models.CharField(max_length=6, default="000000")
    # The boolean is sent is needed for our staff. As they need to be able to filter the orders to complete them
    is_sent = models.BooleanField(default=False)
    # The parcels tracking code needs to be entered by our staff after they've sent the parcel
    delivery_searching_code = models.CharField(max_length=200, null=True)
    # The expiration date is used internally, as we delete every order which is not paid after 7 weeks
    expiration_date = models.DateTimeField()
    is_cash_on_delivery = models.BooleanField(default=False)
    # As our customers can use vouchers that information is also saved and as a default no voucher is used and thus the value is set to 0.
    discount = models.DecimalField(max_digits=5, decimal_places=2, validators=[
        MinValueValidator(Decimal('0.00'))])
    # refund is done manually, as our staff needs to check the damage
    # refund is carried out via PayPal REST SDK (see paypal_payment.py)
    # Once the refund was issued or the case was closed, that case can be closed or rather that boolean can be set to true
    is_refunded = models.BooleanField(default=False)

    @ property
    # @property is used to return a property attribute, which e.g. allows the use of getters and setters
    def price(self):
        # We initialize the price with 0
        price = 0
        # and get all the products/components of the order which belong to the current order
        components = OrderComponent.objects.filter(order=self)
        # Then we loop through all of the products in that oder
        for component in components:
            # And add the price which is the unit price times the quantity to the price
            price += (component.price * component.quantity)
            # to return the total price of the order
        return price

    @ property
    # @property is used to return a property attribute, which e.g. allows the use of getters and setters
    def total_price(self):
        # The total price is the current price plus the delivery price minus the discount
        return self.price + self.delivery_price - self.discount

    def id_with_zeroes(self):
        # The order code is returned which always has six digits
        return str(self.id).zfill(6)

    def __str__(self):
        # To string method which starts with the order number
        return "#" + str(self.id).zfill(6) + ": " + str(self.user) + ' - ' + str(self.price + self.delivery_price - self.discount) + " €"

    @ property
    # @property is used to return a property attribute, which e.g. allows the use of getters and setters
    def is_completed(self):
        # We take all of the components which belong to the order
        components = OrderComponent.objects.filter(order=self)
        # and loop through all of the products in said order
        for component in components:
            # If at least one component is not completed, i.e. ready for shipment
            if component.is_completed == False:
                # Then the entire order is not completed, i.e. ready for shipment
                return False
        # If every component is packaged, the order is ready to be shipped and thus completed
        return True


class DeliveryType(models.Model):
    # The name of the delivery must be unique, as it is used by the customer to identity the delivery type
    name = models.CharField(max_length=100, unique=True)
    # The price is a decimal value with 2 decimal places and a price of at least 0.01, unless it is free delivery, but then no price is needed
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[
        MinValueValidator(Decimal('0.00'))])
    # The description can be used to inform the customer about the differences in the delivery options
    description = models.CharField(max_length=300)

    def __str__(self):
        # To string menthod
        return self.name + ' (' + self.description + ')' + ' - ' + str(self.price) + ' €'


class OrderComponent(models.Model):
    # A order contains different products - the order components and thus the order is needed
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    # Of course the product is needed for every component, but it should not be deleted, if the order component gets deleted
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    # The price is needed - just as with the delivery type
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[
        MinValueValidator(Decimal('0.01'))])
    # This boolean tells us whether the product is ready to ship or not. In its default it is not ready, as the product was not packaged yet.
    is_completed = models.BooleanField(default=False)
    # The quantity is initially one, but as the customer can choose to by more than one product of the same type, the quantity is needed, as we need to send the bought amount
    quantity = models.IntegerField(
        default=1, validators=[MinValueValidator(1)])

    def full_price(self):
        # The full price is the price times the quantity for every order component (i.e. product)
        return self.price * self.quantity

    def __str__(self):
        # To string method which starts with the number sign
        return "#" + str(self.order.id) + ": " + str(self.product.name)

cart/templates/cart/checkout.html
{% extends "shop/base.html" %}
<!-- humanize is used to improve the readability of the figures -->
{% load humanize %}
{% load static %}

{% block title %}
Shopping cart
{% endblock %}

{% block content %}

<style>
    /* If one hovers over the image, it gets resized (bigger) */
    #img:hover {
        width: 300px;
        height: 300px;
        /* The transition makes it look rather smooth */
        transition: 2s ease-in-out;
    }
</style>

<!-- We need to have a product in the cart and this is the case if the total price is higher than 0, as one needs to pay at least 0.01€, as that is the minimal price for a product -->
{% if cart.get_total_price > 0 %}
<!-- If we have at least one product in the users cart, we can show the cart to the user -->
<h1 class="text-success">Shopping cart</h1>
<!-- It fills the entire space the div provides -->
<div class="table-responsive">
    <table class="table cart">
        <thead>
            <!-- We define all of the table headers -->
            <tr class="border-bottom ">
                <th>Picture</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Delete</th>
                <th>Price per unit</th>
                <!-- The (total) price is displayed on the right side -->
                <th class="num text-right">Price</th>
            </tr>
        </thead>
        <tbody>
            <!-- We go through every item in the users cart -->
            {% for item in cart %}
            <!-- with is used here to simply use product instead of item.product -->
            {% with product=item.product %}
            <tr>
                <td>
                    <!-- One can click on the image to get back to the product detail page of that particular item -->
                    <a href="{{ product.get_absolute_url }}">
                        <!-- If the product image exists, it is shown. Otherwise a image not found picture is show in its place -->
                        <img id="img"
                            src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-image.png' %}{% endif %}"
                            height="50" width="50">
                    </a>
                </td>
                <!-- The customer can also click on the product name to get to the product detail page of that particular product -->
                <td><a href="{{ product.get_absolute_url }}" class="text-success text-decoration-none">
                        <!-- The product name is thus displayed in a colour which is used throughout our site for styling and interactions to make it more obvious to the user that he/she can interact with it -->
                        {{ product.name }}
                    </a></td>
                <td>
                    <!-- The user can click on the + to increase the quantity of that particular product by one -->
                    <form action="{% url 'cart:cart_add' product.id %}" method="post" class="pt-2">
                        <select hidden="hidden" name="quantity" id="id_quantity" value="quantity">
                            <!-- The customer can thus take as many product as he/she needs -->
                            <option value="1">1</option>
                        </select>
                        <!-- Cross-site request forgery protection -->
                        {% csrf_token %}
                        <button type="submit" class="fas fa-plus text-dark">
                        </button>
                    </form>
                    <!-- The item quantity is displayed for every product, i.e. number of items the user wants to buy per product -->
                    {{ item.quantity }}
                    <!-- Of course, the customer can also decrease the number of items in his/her cart -->
                    <form action="{% url 'cart:cart_remove_one' product.id %}" method="post" class="pt-2">
                        <select hidden="hidden" name="quantity" id="id_quantity" value="quantity">
                            <!-- Considering that the value might already be one before pressing the -. In that case the item gets deleted from the cart. -->
                            <!-- This is handled by the backend though -->
                            <option value="-1">1</option>
                        </select>
                        <!-- Cross-site request forgery protection -->
                        {% csrf_token %}
                        <button type="submit" class="fas fa-minus text-dark"></button>
                    </form>
                </td>
                <!-- If a user wants to delete a product from his/her cart without pressing the minus button multiple times, that option is provided as well -->
                <td><a href="{% url 'cart:cart_remove' product.id %}" class="fas fa-trash text-danger"></a></td>
                <!-- The red trash can indicates that the user can delete that item from the cart -->
                <td class="num"><span class="d-none d-md-block d-xl-block d-lg-block">{{ item.price }} €</span>
                </td>
                <!-- The total price per item is shown as well -->
                <td class="num text-right">{{ item.total_price }} €</td>
            </tr>
            {% endwith %}
            {% endfor %}
            <!-- If the user has entered a valid coupon, we need to display that information -->
            {% if cart.coupon %}
            <tr>
                <!-- Thus we add some more information to the users cart -->
                <td colspan="5"></td>
                <!-- We get the total price of the cart -->
                <td class="num border-top text-right">Total price: {{ cart.get_total_price }} €</td>
            </tr>
            <tr>
                <!-- But that is not enough, as we want to show the voucher and the new total price as well -->
                <td colspan="5"></td>
                <!-- Thus the name of the coupon code is displayed to the user -->
                <td class="num border-top text-right">Coupon code: "{{ cart.coupon.code }}"
                    <!-- Followed by the percentage discount the voucher provides -->
                    (-{{ cart.coupon.discount|floatformat:2|intcomma }}%)
                    <!-- The amount the user saves by using the voucher is shown too -->
                    -{{ cart.get_discount|floatformat:2|intcomma }} €
                </td>
            </tr>
            <tr>
                <td colspan="5"></td>
                <td class="num border-top text-right">Total:
                    <!-- Finally, the new cart total (after using the voucher) is shown to the customer -->
                    {{ cart.get_total_price_after_discount|floatformat:2|intcomma }} €
                </td>
            </tr>
            {% else %}
            <tr>
                <!-- If no voucher was used by the customer (or it wasn't valid), -->
                <td colspan="5"></td>
                <!-- we solely need to show the total value of the goods in the users cart -->
                <td class="num border-top text-right">Total: {{ cart.get_total_price }} €</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>

<!-- A small form to add a coupon is shown below the cart -->
<span class="float-left">Add &nbsp</span>
<!-- The user can swap the coupon with another coupon anytime -->
<form action="{% url 'coupons:apply' %}" method="post">
    <!-- The CouponApplyForm is a simple textfield -->
    {{ coupon_apply_form }}
    <!-- One cannot send an empty string, but needs to enter a code for it to work -->
    <input class="btn btn-secondary btn w-25" type="submit" value="Coupon">
    <!-- Cross-site request forgery protection -->
    {% csrf_token %}
</form>
<!-- Just some information to the user that he/she doesn't need to try whether two or more coupons can be added to the same cart/order -->
<p class="font-weight-light text_small">You can use only one coupon per order</p>

<p class="text-right mt-4 mb-4">
    <!-- Only logged in users can purchase products in our store -->
    <!-- We wanted to allow anonymous users to checkout as well, but considering the effort which would go into securing everything,
        we decided against it for now, but that would certainly be something to add to the webshop later on -->
    {% if user.is_authenticated %}
    <!-- Thus, a logged in user can decide to get back to the shop to buy more products -->
    <a href="{% url 'shop:product_list' %}" class="button light btn btn-success btn-lg">Continue shopping</a>
    {% else %}
    <!-- If the user is not authenticated yet, the option to login or register is shown instead  -->
    <a href="{% url 'account:login' %}" class="button light btn btn-success btn-lg">Login </a>
    <strong style="font-size: large;">or</strong>
    <a href="{% url 'account:register' %}" class="button light btn btn-success btn-lg">Register</a><br />
    </br /><span class="h5">You must be logged in to make a purchase!</span>
    {% endif %}

</p>

<form method="post" class="border-top">
    <!-- Of course a logged in user has more options than just to go back to the shop -->
    {% if user.is_authenticated %}
    <!-- If he/she has products in his/her cart, the person can proceed with the checkout -->
    {% if cart.get_total_price > 0 %}
    <!-- Thus, we display the information that the delivery is free, if one buys for 65€ or more -->
    <center><i>For orders over {{ free_delivery_price }}€ shipment is free!<br /></i>
    </center>
    <!-- If the user fulfills the condition, he/she gets the message that the delivery is free -->
    {% if cart.get_total_price >= free_delivery_price %}
    <center><i>SYou are entitled to free delivery. The delivery cost will not be added to your added to your order.</i>
    </center>
    {% endif %}
    <!-- Otherwise, the user can choose between the different delivery methods -->
    <h3><i class="fas fa-truck mt-4 mb-2"></i> Shippment method</h3>
    <!-- Cross-site request forgery -->
    {% csrf_token %}
    <!-- Hence, we cycle through all of the existing delivery options -->
    {% for radio in delivery_form.delivery_type %}
    <!-- The customer can click on the radio button to choose the delivery option which suits him/her best -->
    <label for="{{ radio.name }}">
        <span class=" blockquote ml-4">{{ radio }}</span>
        <!-- Thus, the delivery method is mentioned next to the radio button -->
        {{ radio.name }}<br />
    </label>

    <br />
    {% endfor %}
    {% endif %}
    {% endif %}

    <!-- Another button to place the order is shown on the right side after the delivery method -->
    <p class="text-right">
        <!-- It is, however, only shown if the user is authenticated and has at least one product in his/her cart -->
        {% if cart.get_total_price > 0 and user.is_authenticated %}
        <!-- One could adjust the number, if a minimal value for the purchase should be set, but as our customers have to pay the delivery
            (until they reach a certain value of goods in their cart), we let the user buy as many or as little products as he/she wants -->
        <button type="submit" class="btn btn-success btn-lg">Purchase and pay</button>
        {% endif %}
    </p>
</form>

{% else %}
<!-- If the total price of the users cart is less than 0.01, that means that the user currently has no products in his/her cart -->
<h1 class="display-4 p-3 text-center"> Your cart is currently empty.</h1>
<!-- The user can click on the icon to get to the product list to start adding products to his/her cart -->
<a href="{% url 'shop:product_list' %}" style="color:darkgreen">
    <p class="text-center"><i class="fas fa-cart-plus display-1 p-4 text-center"></i></p>
</a>

{% endif %}

{% endblock %}

cart/templates/cart/order_complete.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Order processed successfully
{% endblock %}

{% block content %}

<div>
	<h3>Thank you for shopping GreenOasis!</h3> <br />
	<!-- The user receives the message regarding his/her purchase -->
	{{ message }}
	<br /> <br />
	<!-- The customer needs to know his/her order number, if something goes wrong - e.g. needed for complaints -->
	<h3>Your order number is: {{ order.id|stringformat:"06d" }}</h3> <br />
	<!-- The customer can view his/her order history, which at least includes the currently placed order -->
	<a href="{% url 'profile:show_orders' %}" style="color:darkgreen"><strong>Display order history</strong></a>
	<p></p>
	<!-- Moreover, the user has the option to get back to the front page -->
	<p><strong>Zurück zur <a href="/" style="color:green">Frontpage</a>.</strong></p>
	<br />
</div>

<!-- Newsletter subscription -->
<center>
	<a href="{% url 'newsletter:newsletter_registration' %}"><img src="{% static 'images/Newsletter.jpg' %}"
			width='60%' /></a>
</center> <br />

{% endblock %}