Solkraft/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from shop import views

# These are the root url patterns

urlpatterns = [
    # The admin panel is included
    path('admin/', admin.site.urls),
    # As well as all the urls from the different applications that we've created
    path('questions/', include('questions.urls')),
    path('plate/', include('django_spaghetti.urls')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls')),
    path('profile/', include('customer.urls', namespace='profile')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('parameter-autocomplete/', views.ParameterAutocomplete,
         name='parameter-autocomplete'),
    # and social-auth from Django social auth to add registration and login via social media
    # The login with Facebook and Google worked fine, but solely with an older version of django-social-auth which sometimes led to installation problems and thus we removed it from our website
    # path('social-auth/', include('social_django.urls', namespace='social')),
    # and two more paths from our side
    path('newsletter/', include('newsletter.urls')),
    path("password_reset", views.password_reset_request, name="password_reset"),
]

# Setting the media folder
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

# The name is used to identify the app
# If one wants to use any function, e.g. allblogs, one needs to write blog:allblogs, instead of simply allblogs
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'blog'

urlpatterns = [
    path('', views.allblogs, name='allblogs'),
    path('games.html', views.games, name='games'),
    # The blog post is identified by it's id, which is an intger
    path('<int:post_id>', views.blog_post, name='blog_post')
]

cart/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

# The name is used to identify the app
# If one wants to use any function, e.g. cart_add, one needs to write cart:cart_add, instead of simply cart_add
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'cart'

urlpatterns = [
    # The checkout shows the cart details, offers a voucher option, a delivery selection and offers the option to place an order
    path('checkout/', views.cart_detail, name='cart_detail'),
    # Cart add is used to add a selected number of products to the cart
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    # Cart_add_one solely adds the product to the cart once (used outside of the product detail page and for the + button in the cart)
    path('add/<int:product_id>/', views.cart_add_one, name='cart_add_one'),
    # Cart remove deletes the product from the cart
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    # Cart remove one decreases the quantity by one (though it was implemented in a way, which makes it possible to decrease the quantity by a given amount)
    path('remove_one/<int:product_id>/',
         views.cart_remove_one, name='cart_remove_one'),
    #  Of course, checkout is possible
    path('cart_checkout/<int:id>', views.cart_checkout, name='cart_checkout'),
    # The customer needs to choose a shipping address
    path('choose_address/<int:id>', views.choose_address, name='choose_address'),
    # If the order is complete, a template is shown which summarizes the important information
    path('order_complete/', views.order_complete, name='order_complete'),
    path('order_bank_transfer', views.order_bank_transfer,
         name='order_bank_transfer'),
    # If the user pays via bank transfer, another method is needed, as order_complete works with PayPal
    path('cash_on_delivery', views.cash_on_delivery, name='cash_on_delivery'),
    # If the user wants to collect the products from our Solkraft shop, the procedure differs as well
    path('collection', views.collection, name='collection')

]

newsletter/urls.py
from . import views
from django.urls import path

# The name is used to identify the app
# If one wants to use any function, e.g. new, one needs to write newsletter:new, instead of simply new
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'newsletter'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('new//confirm/', views.confirm, name='confirm'),
    path('delete/', views.delete, name='delete'),
    path('newsletter_registration/', views.newsletter_registration,
         name="newsletter_registration"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

# The name is used to identify the application
# If one wants to use any function, e.g. add_to_wishlist, one needs to write shop:add_to_wishlist, instead of simply add_to_wishlist
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
# Another benefit is that the same name can be given to another path in a different application
app_name = 'shop'

urlpatterns = [
    # Our staff works with the admin panel for the most part, though they also have their dedicated app with templates/function specifically defined to make their work easier for them
    path('admin/', admin.site.urls),
    #     In the home page 4 random products are displayed (they are different every time you'll load the page)
    path('', views.random_products, name='random_products'),
    #     We added some static pages for information, e.g. this about us and the below terms of service page
    path('about_us.html', views.about_view, name='about_us'),
    path('terms_of_service.html', views.terms_view, name='terms_of_service'),
    #     A wishlist with all needed functions was created as well
    path('wishlist/', views.WishListView.as_view(), name='wishlist'),
    #     The product can be added from the product page and the product cards in the product_list, random_products and search
    path('add_to_wishlist/<slug:product_slug>',
         views.add_to_wishlist, name="add_to_wishlist"),
    #     And the wishlist can be deleted in the product page and inside the wishlist
    #     If a user tries to delete an item from the list, which isn't in his/her wishlist, the user is redirected to the wishlist without any changes
    path('delete_from_wishlist/<slug:product_slug>', views.delete_from_wishlist,
         name='delete_from_wishlist'),
    #     More static sites
    path('privacy_policy.html', views.privacy_view, name='privacy_policy'),
    path('shipping_policy.html', views.policy_view, name='shipping_policy'),
    #     The summary contains information about the offered services and allows the user to register for the plant workshops
    path('summary.html', views.summary_view, name='summary'),
    #     The products are displayed in a list and pagination exists which ensures that our website doesn't take too long to load
    path('products/', views.product_list, name='product_list'),
    path('<int:page>/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    #     The category slug is needed to ensure that only the products of a specific category are shown, if a category is selected by the user
    path('<slug:category_slug>/<int:page>/',
         views.product_list, name='product_list_by_category'),
    #     Of course every item has its dedicated page with further information about it
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    #     Our user can add reviews, but they can also delete their own reviews
    path('delete_review/<int:id>', views.delete_review,
         name='delete_review'),
    #     A search was implemented as well. It isn't too smart, but therefore it wasn't simply taken from an existing source but created by ourselves
    #     We had to use re_path, since we had to add the dollar sign at the end to ensure that the search works well for every type of user input
    re_path(r'^searching/<str:phrase>/$',
            views.searching, name='searching'),
    #   Pagination shouldn't be needed for the search as of now, but potentially the webshop will add more products later on and someday it might very well be needed
    path('searching/<int:page>/<str:phrase>',
         views.searching, name='searching'),
]

cart/forms.py
from django import forms
# We need the Order and DeliveryType, which we've defined in the models.py file
from .models import DeliveryType, Order

# The customer can add a different quantity of a product to the shopping cart. In this case an integer between 1 to 20.
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    # The quantity is needed and it has to be an integer. Thus, we have to force the quantity to be an integer
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    # The update is used to update the quantity in the cart. Initially, no update exists/is needed and thus it is false
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)


class CartRemoveProductForm(forms.Form):
    # The customer can delete a product from the cart entirely. The quantity of the product doesn't matter.
    # The product is deleted from the cart regardless of the quantity.
    quantity = forms.TypedChoiceField(
        choices=[(i, str(i)) for i in range(-1, 21)],
        coerce=int)
    # As with the add function we have to ensure that the quantity is indeed an integer


class ChooseDeliveryType(forms.Form):
    # The customer can choose any of the offered delivery types, unless a free delivery is chosen (if the quantity in the cart is high enough)
    delivery_type = forms.ModelChoiceField(queryset=DeliveryType.objects.all(
    ), widget=forms.RadioSelect, required=True, initial=1)
    # Radio buttons are used, since only one option can be chosen


class AddressForm(forms.Form):
    # The address form contains the name, which is the given name or also given names
    name = forms.CharField(label='First name', max_length=100)
    # The surname can consist of one or many names
    surname = forms.CharField(label='Surname', max_length=100)
    # The street and the house number are needed, as the address is used to send the product to the customer
    street = forms.CharField(label='Street', max_length=150)
    number = forms.CharField(label='House number', max_length=10)
    # The city and postal code are needed to ensure that the parcel arrives at the right place
    city = forms.CharField(label='City', max_length=100)
    postal_code = forms.IntegerField(
        label='Postal code', min_value=5, max_value=99999)

shop/forms.py
from dal import autocomplete
from .models import Review, Parameter, Description, Product, ExtraPhoto
from django import forms
from django.contrib.auth.models import User


class ReviewForm(forms.ModelForm):
    # Meta means that we use the information from another already existing model, instead of creating new fields for the form which would be the same in this case
    class Meta:
        # The review forms takes its fields from the Review model (located in the models.py)
        model = Review
        # and we solely take the fields body and rating, as body is the text the user writes and the rating is the number of stars
        fields = ('body', 'rating', )


class DescriptionForm(forms.ModelForm):
    # As we only have to change the meta information in the Description model, if we want to change e.g. the form, the maintainability is improved by using Meta
    class Meta:
        # The description form takes all the fields from the description model
        model = Description
        fields = ('__all__')
        # we use autocomplete to autocomplete the descriptions (method located in views.py)
        widgets = {
            'parameter': autocomplete.ListSelect2(url='parameter-autocomplete', forward=['product']
                                                  )
        }

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

<!-- If a category was chosen, the category name is used as the title -->
{% block title %}
{% if category %}{{ category.name }}
{% else %}Produkte{% endif %}
{% endblock %}
<!-- Otherwise all products and thus "Produkte" is used as the title -->
{% block content %}

<div class="row col-lg-15">
    <!-- We start with showing the categories -->
    <div class="col-lg-10 d-none d-xl-block d-lg-block ">
        <div id="sidebar" class="list-group border pl-3 pr-4 pt-2 pb-4 rounded-lg bg-success">
            <!-- The categories need to be checked therefore -->
            <p class="text-uppercase text-overflow h5 text-white">Categories</p>
            <table>
                <tr>
                    <th>
                        <!-- One can get to the product list as a total by clicking on "Alle" -->
                        <a href="{% url 'shop:product_list' %}"
                            class="text-left text-uppercase text-decoration-none text-overflow mt-2 text-white">
                            <!-- If no category was used, one can simply show the product list, as it is the case, if one clicks on "Alle" -->
                            {% if not category %} {% endif %}
                            ALL
                        </a>
                    </th>
                    <!-- Otherwise we loop through all categories -->
                    {% for category in categories %}
                    <!-- and get the absolute url of the category in question -->
                    <th><a href="{{ category.get_absolute_url }}"
                            class="text-center text-uppercase text-decoration-none mt-2 text-overflow text-white">
                            <!-- The category name is shown, so that the user can choose the right category -->
                            {{ category.name }}
                        </a>
                    </th>
                    {% endfor %}
                </tr>

            </table>
        </div>
    </div>

    <!-- The products are at least as important and are shown below -->
    <div class="product-list col-md-12 col-lg-10 text-center">
        <div class="row ">
            <!-- We loop through all products -->
            {% for product in products %}
            <!-- Get the url for the product, so that the user can easily get to the product detail page -->
            <a href="{{ product.get_absolute_url }}">
                <div class="col-md-6 col-lg-4">
                    <div class="item mb-4">
                        <!-- The content is shown centered -->
                        <div id="img" class="text-center">
                            <!-- Either the prouct image or the image not found picture are shown -->
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}
							{% static 'img/no-image.png' %} {% endif %}" class="img-fluid mt-4 mb-4">
                        </div>
                        <!-- One can add the product to the wishlist by clicking on the red heart -->
                        <a href="{% url 'shop:add_to_wishlist' product.slug %}" class="text-danger"><i
                                class="fas fa-heart"></i>
                        </a>
                        <div id="description">
                            <!-- The absolute product URL is taken once more for a easy way to the product details page -->
                            <a href="{{ product.get_absolute_url }}"
                                class="text-overflow text-uppercase text-decoration-none text-success">
                                <!-- The product name is shown below -->
                                <string class="text-overflow m-0">
                                    {{ product.name }}
                                </string>
                            </a>
                        </div>

                        <div id="price" class="mt-2">
                            <!-- If the new price is not zero, i.e. the price was reduced, -->
                            {% if product.new_price != 0 %}
                            <!-- The ne product price is shown -->
                            <h4> {{ product.new_price }} €
                                <!-- and the percentage price reduction is shown in red to alert the customer about this offer -->
                                <span class="font-weight-bold text-danger">
                                    -{{ product.sales_percent }}%</span>
                            </h4>
                            {% else %}
                            <!-- Otheriwse the "normal" product price is simply shown -->
                            <h4> {{ product.price }} €</h4>
                            {% endif %}

                        </div>
                        <div id="add" class="pl-3">
                            <!-- The customer has the option to add the product to the cart -->
                            <form action="{% url 'cart:cart_add_one' product.id %}" method="post" class="pt-2">
                                <select hidden="hidden" name="quantity" id="id_quantity" value="quantity">
                                    <!-- In this case they can only add the item to the cart once, which is usally what the customer wants (and it looks somewhat better) -->
                                    <option value="1">1</option>
                                </select>
                                <!-- Cross-site request forgery protection -->
                                {% csrf_token %}
                                <!-- Add to cart button -->
                                <button type="submit"
                                    class="btn btn-block btn-success bg-success btn-circle btn-icon-left" value="Add">
                                    <i class="fa fa-shopping-cart fa-lg"></i> Add
                                </button>
                            </form>
                        </div>

                    </div>
                </div>
            </a>

            {% endfor %}
        </div>
    </div>
</div>

<!-- The page navigation works in the backend but of course needs to be shown in the frontend -->
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        <!-- If a page before the currently displayed page exists, the "Vorherige" button is shown to get back to that page -->
        {% if products.has_previous %}
        <li class="page-item">
            <a class="page-link text-success"
                href="{% url 'shop:product_list' products.previous_page_number %}">Vorherige</a>
        </li>
        {% else %}
        <!-- Otherwise we hide that information, as it wouldn't work anyways -->
        <li class="page-item " hidden="hidden">
            <a class="page-link text-success deactivated">Vorherige</a>
        </li>

        {% endif %}

        <!-- We get every existing page -->
        {% for page in paginator.page_range %}
        <!-- And display the correct number -->
        {% if page == products.number %}
        <!-- If we are on said number, it is highlighted in darkgreen -->
        <li class="page-item active"><span class="page-link ">{{ page }}</span><span class="sr-only ">(current)</span>
        </li>
        <!-- Otherwise we can click on the page number to get to said page -->
        {% else %}
        <!-- Once can get to the page, one clicks on and it always shows the same products -->
        <li class="page-item "><a class="page-link text-success" href="{% url 'shop:product_list' page %}">
                {{ page}}</a></li>
        {% endif %}

        {% endfor %}
        <!-- If a following page exists -->
        {% if products.has_next %}
        <li class="page-item">
            <!-- The "Nächste" button is shown -->
            <a class="page-link text-success" href="{% url 'shop:product_list' products.next_page_number %}">Nächste</a>
        </li>
        {% else %}
        <!-- Otherwise, we hide that button, as it wouldn't work anyways -->
        <li class="page-item" hidden="hidden">
            <a class="page-link deactivated text-success">Nächste</a>
        </li>
        {% endif %}
    </ul>
</nav>
<!-- Newsletter subscription -->
<center>
    <a href="{% url 'newsletter:newsletter_registration' %}"><img src="{% static 'images/Newsletter.jpg' %}"
            width='60%' /></a>
</center><br />

{% endblock %}

shop/templates/shop/product/searching.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Suchergebnisse
{% endblock %}

{% block content %}

{% if not products %}
<!-- It could be that there's no available product which fits the search phrase -->
<h1 class="display-4 p-4 text-center">Wir konnten kein passendes Produkt finden.</h1>
<!-- In that case we inform the customer about that and give him/her the option to view all of our products -->
<a href="{% url 'shop:product_list' %}" style="color:darkgreen">
	<p class="text-center"><i class="fas fa-times-circle display-1 p-4 text-center" aria-hidden="true"></i></p>
</a>
{% else %}
<!-- Otherwise at least one product was found which fits the search phrase -->
<div class="product-list col-12 text-center">
	<div class="row ">
		<!-- In that case we loop through all the products we've found -->
		{% for product in products %}
		<!-- And get the absolute URL, so that the customer can view the product details page with a single click -->
		<a href="{{ product.get_absolute_url }}">
			<!-- Whilst the link is great, we need to display actual information -->
			<div class="col-md-6 col-lg-3">
				<!-- Thus, we need to show the product image -->
				<div class="item mb-4">
					<div id="img" class="text-center">
						<!-- If the product image doesn't exist, we will show a image not found picture instead -->
						<img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-image.png'%} 
						{% endif %}" class="img-fluid mt-4 mb-4">
					</div>
					<!-- The red heart is used to add the product to the wishlist -->
					<a href="{% url 'shop:add_to_wishlist' product.slug %}" class="text-danger"><i
							class="fas fa-heart"></i>
					</a>
					<div id="description">
						<!-- One can also click on the product name to get to the product details page -->
						<a href="{{ product.get_absolute_url }}"
							class="text-overflow text-uppercase text-decoration-none text-success">
							<!-- Thus, we need to show the product name -->
							<string class="text-overflow m-0">
								{{ product.name }}
						</a>
						</string>
					</div>
					<!-- Of course, the price is also very important -->
					<div id="price" class="mt-2">
						<!-- Hence, we need to check whether a discount price was added -->
						{% if product.new_price != 0 %}
						<!-- If one exists, we show the new price -->
						<h4> {{ product.new_price }} €
							<!-- Followed by the percentage discount in red to alert the user about the offer -->
							<span class="font-weight-bold text-danger">
								-{{product.sales_percent }}%</span>
						</h4>
						{% else %}
						<!-- Otherwise the "normal" price is simply shown -->
						<h4> {{ product.price }} €</h4>
						{% endif %}

						<div id="add" class="pl-3">
							<!-- The customer can add the product to the cart right away -->
							<form action="{% url 'cart:cart_add_one' product.id %}" method="post" class="pt-2">
								<!-- In this case one product is added to the cart -->
								<select hidden="hidden" name="quantity" id="id_quantity" value="quantity">
									<!-- This can be adjusted in the product details page or directly in the cart -->
									<option value="1">1</option>
								</select>
								<!-- Cross-site request forgery protection -->
								{% csrf_token %}
								<!-- One can add the product to the cart with a simple click -->
								<button type="submit"
									class="btn btn-block btn-success bg-success btn-circle btn-icon-left" value="Add">
									<!-- In that case the customer gets redirected to his/her cart -->
									<i class="fa fa-shopping-cart fa-lg"></i> Add
								</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</a>

		{% endfor %}
	</div>
	<!-- Page naviation is added as well -->
	<nav aria-label="Page navigation">
		<!-- Currently we do not have enough possible results to actually use it, but the webshop could increase in size -->
		<ul class="pagination justify-content-center">
			<!-- We check whether a previous page exists -->
			{% if products.has_previous %}
			<li class="page-item">
				<!-- If that is the case, we add a "Vorherige" button to get back-->
				<a class="page-link text-success"
					href="{% url 'shop:searching' products.previous_page_number phrase %}">Vorherige
				</a>
			</li>
			{% else %}
			<!-- Otherwise we hide that button, as it wouldn't work anyways -->
			<li class="page-item">
				<a class="page-link desativated" hidden="hidden">Vorherige </a>
			</li>

			{% endif %}
			<!-- We get every existing page -->
			{% for page in paginator.page_range %}
			<!-- And display the correct number -->
			{% if page == products.number %}
			<!-- If we are on said number, it is highlighted in darkgreen -->
			<li class="page-item active"><span class="page-link">{{ page }}</span><span class="sr-only">(current)</span>
			</li>
			{% else %}
			<!-- Otherwise we can click on the page to get to that site -->
			<li class="page-item "><a class="page-link text-success" href="{% url 'shop:searching' page phrase %}">
					{{ page }}</a>
			</li>
			{% endif %}

			{% endfor %}
			<!-- If another page exists (next page exists) -->
			{% if products.has_next %}
			<li class="page-item">
				<!-- We can get to it by (either clicking on the page number or by) clicking on the "Nächste" button -->
				<a class="page-link" href="{% url 'shop:searching' products.next_page_number phrase %}">Nächste</a>
			</li>
			{% else %}
			<!-- Otherwise we can hide the "Nächste" button, as it wouldn't work anyways -->
			<li class="page-item">
				<a class="page-link desativated" hidden="hidden">Nächste</a>
			</li>
			{% endif %}
		</ul>
	</nav>
</div>
{% endif %}
<!-- Newsletter subscription -->
<center>
	<a href="{% url 'newsletter:newsletter_registration' %}"><img src="{% static 'images/Newsletter.jpg' %}"
			width='60%' /></a>
</center><br />
{% endblock %}