Solkraft/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from shop import views

# These are the root url patterns

urlpatterns = [
    # The admin panel is included
    path('admin/', admin.site.urls),
    # As well as all the urls from the different applications that we've created
    path('questions/', include('questions.urls')),
    path('plate/', include('django_spaghetti.urls')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls')),
    path('profile/', include('customer.urls', namespace='profile')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('parameter-autocomplete/', views.ParameterAutocomplete,
         name='parameter-autocomplete'),
    # and social-auth from Django social auth to add registration and login via social media
    # The login with Facebook and Google worked fine, but solely with an older version of django-social-auth which sometimes led to installation problems and thus we removed it from our website
    # path('social-auth/', include('social_django.urls', namespace='social')),
    # and two more paths from our side
    path('newsletter/', include('newsletter.urls')),
    path("password_reset", views.password_reset_request, name="password_reset"),
]

# Setting the media folder
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

# The name is used to identify the app
# If one wants to use any function, e.g. allblogs, one needs to write blog:allblogs, instead of simply allblogs
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'blog'

urlpatterns = [
    path('', views.allblogs, name='allblogs'),
    path('games.html', views.games, name='games'),
    # The blog post is identified by it's id, which is an intger
    path('<int:post_id>', views.blog_post, name='blog_post')
]

cart/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

# The name is used to identify the app
# If one wants to use any function, e.g. cart_add, one needs to write cart:cart_add, instead of simply cart_add
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'cart'

urlpatterns = [
    # The checkout shows the cart details, offers a voucher option, a delivery selection and offers the option to place an order
    path('checkout/', views.cart_detail, name='cart_detail'),
    # Cart add is used to add a selected number of products to the cart
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    # Cart_add_one solely adds the product to the cart once (used outside of the product detail page and for the + button in the cart)
    path('add/<int:product_id>/', views.cart_add_one, name='cart_add_one'),
    # Cart remove deletes the product from the cart
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    # Cart remove one decreases the quantity by one (though it was implemented in a way, which makes it possible to decrease the quantity by a given amount)
    path('remove_one/<int:product_id>/',
         views.cart_remove_one, name='cart_remove_one'),
    #  Of course, checkout is possible
    path('cart_checkout/<int:id>', views.cart_checkout, name='cart_checkout'),
    # The customer needs to choose a shipping address
    path('choose_address/<int:id>', views.choose_address, name='choose_address'),
    # If the order is complete, a template is shown which summarizes the important information
    path('order_complete/', views.order_complete, name='order_complete'),
    path('order_bank_transfer', views.order_bank_transfer,
         name='order_bank_transfer'),
    # If the user pays via bank transfer, another method is needed, as order_complete works with PayPal
    path('cash_on_delivery', views.cash_on_delivery, name='cash_on_delivery'),
    # If the user wants to collect the products from our Solkraft shop, the procedure differs as well
    path('collection', views.collection, name='collection')

]

newsletter/urls.py
from . import views
from django.urls import path

# The name is used to identify the app
# If one wants to use any function, e.g. new, one needs to write newsletter:new, instead of simply new
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
app_name = 'newsletter'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('new//confirm/', views.confirm, name='confirm'),
    path('delete/', views.delete, name='delete'),
    path('newsletter_registration/', views.newsletter_registration,
         name="newsletter_registration"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

# The name is used to identify the application
# If one wants to use any function, e.g. add_to_wishlist, one needs to write shop:add_to_wishlist, instead of simply add_to_wishlist
# One benefit of that is that one directly knows where the view function is located, which improves maintainability
# Another benefit is that the same name can be given to another path in a different application
app_name = 'shop'

urlpatterns = [
    # Our staff works with the admin panel for the most part, though they also have their dedicated app with templates/function specifically defined to make their work easier for them
    path('admin/', admin.site.urls),
    #     In the home page 4 random products are displayed (they are different every time you'll load the page)
    path('', views.random_products, name='random_products'),
    #     We added some static pages for information, e.g. this about us and the below terms of service page
    path('about_us.html', views.about_view, name='about_us'),
    path('terms_of_service.html', views.terms_view, name='terms_of_service'),
    #     A wishlist with all needed functions was created as well
    path('wishlist/', views.WishListView.as_view(), name='wishlist'),
    #     The product can be added from the product page and the product cards in the product_list, random_products and search
    path('add_to_wishlist/<slug:product_slug>',
         views.add_to_wishlist, name="add_to_wishlist"),
    #     And the wishlist can be deleted in the product page and inside the wishlist
    #     If a user tries to delete an item from the list, which isn't in his/her wishlist, the user is redirected to the wishlist without any changes
    path('delete_from_wishlist/<slug:product_slug>', views.delete_from_wishlist,
         name='delete_from_wishlist'),
    #     More static sites
    path('privacy_policy.html', views.privacy_view, name='privacy_policy'),
    path('shipping_policy.html', views.policy_view, name='shipping_policy'),
    #     The summary contains information about the offered services and allows the user to register for the plant workshops
    path('summary.html', views.summary_view, name='summary'),
    #     The products are displayed in a list and pagination exists which ensures that our website doesn't take too long to load
    path('products/', views.product_list, name='product_list'),
    path('<int:page>/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    #     The category slug is needed to ensure that only the products of a specific category are shown, if a category is selected by the user
    path('<slug:category_slug>/<int:page>/',
         views.product_list, name='product_list_by_category'),
    #     Of course every item has its dedicated page with further information about it
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    #     Our user can add reviews, but they can also delete their own reviews
    path('delete_review/<int:id>', views.delete_review,
         name='delete_review'),
    #     A search was implemented as well. It isn't too smart, but therefore it wasn't simply taken from an existing source but created by ourselves
    #     We had to use re_path, since we had to add the dollar sign at the end to ensure that the search works well for every type of user input
    re_path(r'^searching/<str:phrase>/$',
            views.searching, name='searching'),
    #   Pagination shouldn't be needed for the search as of now, but potentially the webshop will add more products later on and someday it might very well be needed
    path('searching/<int:page>/<str:phrase>',
         views.searching, name='searching'),
]

cart/forms.py
from django import forms
# We need the Order and DeliveryType, which we've defined in the models.py file
from .models import DeliveryType, Order

# The customer can add a different quantity of a product to the shopping cart. In this case an integer between 1 to 20.
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    # The quantity is needed and it has to be an integer. Thus, we have to force the quantity to be an integer
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    # The update is used to update the quantity in the cart. Initially, no update exists/is needed and thus it is false
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)


class CartRemoveProductForm(forms.Form):
    # The customer can delete a product from the cart entirely. The quantity of the product doesn't matter.
    # The product is deleted from the cart regardless of the quantity.
    quantity = forms.TypedChoiceField(
        choices=[(i, str(i)) for i in range(-1, 21)],
        coerce=int)
    # As with the add function we have to ensure that the quantity is indeed an integer


class ChooseDeliveryType(forms.Form):
    # The customer can choose any of the offered delivery types, unless a free delivery is chosen (if the quantity in the cart is high enough)
    delivery_type = forms.ModelChoiceField(queryset=DeliveryType.objects.all(
    ), widget=forms.RadioSelect, required=True, initial=1)
    # Radio buttons are used, since only one option can be chosen


class AddressForm(forms.Form):
    # The address form contains the name, which is the given name or also given names
    name = forms.CharField(label='First name', max_length=100)
    # The surname can consist of one or many names
    surname = forms.CharField(label='Surname', max_length=100)
    # The street and the house number are needed, as the address is used to send the product to the customer
    street = forms.CharField(label='Street', max_length=150)
    number = forms.CharField(label='House number', max_length=10)
    # The city and postal code are needed to ensure that the parcel arrives at the right place
    city = forms.CharField(label='City', max_length=100)
    postal_code = forms.IntegerField(
        label='Postal code', min_value=5, max_value=99999)

shop/forms.py
from dal import autocomplete
from .models import Review, Parameter, Description, Product, ExtraPhoto
from django import forms
from django.contrib.auth.models import User


class ReviewForm(forms.ModelForm):
    # Meta means that we use the information from another already existing model, instead of creating new fields for the form which would be the same in this case
    class Meta:
        # The review forms takes its fields from the Review model (located in the models.py)
        model = Review
        # and we solely take the fields body and rating, as body is the text the user writes and the rating is the number of stars
        fields = ('body', 'rating', )


class DescriptionForm(forms.ModelForm):
    # As we only have to change the meta information in the Description model, if we want to change e.g. the form, the maintainability is improved by using Meta
    class Meta:
        # The description form takes all the fields from the description model
        model = Description
        fields = ('__all__')
        # we use autocomplete to autocomplete the descriptions (method located in views.py)
        widgets = {
            'parameter': autocomplete.ListSelect2(url='parameter-autocomplete', forward=['product']
                                                  )
        }

shop/templates/shop/main.html
{% extends "shop/base.html" %}
{% load static %}

<!-- Now we actually do not necessarily need a title here, but we still added one for completion -->
{% block title %}
Solkraft
{% endblock %}

{% block content %}

<!-- Carousel from Bootstrap -->
<div class="row">
    <div id="carouselExampleIndicators" class="carousel slide col-12" data-ride="carousel">
        <ol class="carousel-indicators">
            <!-- With three images -->
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner rounded-lg">
            <div class="carousel-item active ">
                <!-- One can get to the product list, which shows all of our available products by clicking on any of the slides images -->
                <a href="{% url 'shop:product_list' %}">
                    <img class="d-block w-100 carousel_img"
                        src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.nrel.gov%2Fnews%2Fprogram%2F2021%2Fimages%2F07012021-amr-awards-storage.jpeg&f=1&nofb=1"
                        alt="First slide">
                </a>
            </div>
            <div class="carousel-item">
                <a href="{% url 'shop:product_list' %}">
                    <img class="d-block w-100 carousel_img"
                        src="https://energycentral.com/sites/default/files/styles/article_body/public/ece/nodes/432044/dreamstime_s_189672237.jpg?itok=ZlCA98hf"
                        alt="Second slide">
                </a>
            </div>
            <div class="carousel-item">
                <a href="https://www.solarpowerworldonline.com/wp-content/uploads/2019/09/sunpower-energy-storage.jpg">
                    <img class="d-block w-100 carousel_img"
                        src="https://www.solarpowerworldonline.com/wp-content/uploads/2019/09/sunpower-energy-storage.jpg"
                        alt="Third slide">
                </a>
            </div>
        </div>
        <!-- The controls are active, so that the customer can get back to the previous slide -->
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <!-- Of course, the customer can also get to the next slide, if he/she wants to -->
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <!-- The id recommend is used here, as it is used for the products in most cases, as they usually have the same style -->
    <div id="recommend" class="product-list row  col-md-12 mb-2 mt-4 text-center">
        <!-- We loop through all of our products -->
        {% for product in products %}
        <!-- and display the products -->
        <div class="item col-md-3 mb-2 mt-4">
            <div id="img" class=" text-center">
                <!-- The customer can click on the product information to view the product details page -->
                <a href="{% url 'shop:product_detail' product.id product.slug %}">
                    <!-- If a product image exists, it is shown. Otherwise the image not found picture is displayed -->
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-image.png' %}{% endif %}"
                        class="img-fluid p-2">
                    <!-- Our cstomers can add the product to their wishlist by clicking on the heart icon -->
                    <br /><a href="{% url 'shop:add_to_wishlist' product.slug %}" class="text-danger"><i
                            class="fas fa-heart"></i>
                    </a>
                    <div id="description">
                        <!-- The product name is displayed below the image -->
                        <p class="text-overflow text-uppercase text-decoration-none font-weight-ligh text-success">
                            {{ product.name }}
                        </p>
                    </div>
                </a>
            </div>
            <!-- The price is shown below the product name -->
            <div id="price" class="pl-2">
                <!-- If the new price is zero, that means that there is currently no discount -->
                {% if product.new_price == 0 %}
                <!-- Thus, we can simply show the products price -->
                <h4> {{ product.price }} €</h4>
                {% else %}
                <!-- Otherwise a discounted price exists, which is shown instead of the "normal" product price -->
                <h4> {{ product.new_price }} €
                    <!-- The percentage discount is shown in red text to alert the user about this offer -->
                    <span class="font-weight-bold text-danger">
                        -{{ product.sales_percent }}%</span>
                </h4>
                {% endif %}
            </div>
            <div id="add" class="pl-3">
                <!-- The customer can add a quantity of 1 of the product to his/her cart -->
                <form action="{% url 'cart:cart_add_one' product.id %}" method="post" class="pt-2">
                    <select hidden="hidden" name="quantity" id="id_quantity" value="quantity">
                        <option value="1">1</option>
                    </select>
                    <!-- Cross-site request forgery protection -->
                    {% csrf_token %}
                    <!-- To add the product to ones cart, one has to click on the button below -->
                    <button type="submit" class="btn btn-block btn-success bg-success btn-circle btn-icon-left"
                        value="Add">
                        <i class="fa fa-shopping-cart fa-lg"></i> Add
                    </button>
                </form>
            </div>

        </div>

        {% endfor %}

    </div>
</div>
<!-- Newsletter subscription-->
<center>
    <a href="{% url 'newsletter:newsletter_registration' %}"><img src="{% static 'images/Newsletter.jpg' %}"
            width='60%' /> </a>
</center>
<br />
{% endblock %}